# ctwrap conda package dependencies
name: ctwrap
channels:
  - conda-forge
  - cantera/label/dev
  - defaults
dependencies:
  - python=3.7
  - numpy
  - h5py
  - pint
  - ruamel.yaml
  - cantera
  - setuptools
  - pytest
  - pytest-cov
  - coverage
  - ipython
  - jupyter
  - matplotlib
